### PR TITLE
Reorg files, consolidate styles

### PR DESCRIPTION
**Pull request by ericmasiello**
Consolidated global style rules into styles directory
Create a `<Button>` and `<H1>` component
Moved styles related to a component into its own directory with related component code
Simplify/remove unneeded nested components

### CODE REVIEW

**Comment by ericmasiello** [comment]
This is starting to move toward the direction we discussed last week re: the article i sent. One downside I'm seeing is there's a lot of files called index.js and style.js which could get confusing if you have a lot of them open and are trying to edit them.

**Comment by cmann50** [comment]
Looks good, so merge when ready.
I agree having a bunch of index.js files that have the component code in them is confusing.  I looked around and could only find a small finance app that was organized by feature.  It was doing something similar.  But you'd think you could just use index.js as mostly empty stub that called the container and component with proper file names.  
Did you decide to use the index.js per feature based on an example that I could look at?

**Comment by ericmasiello** [comment]
Hmm. Yeah now that you mention it, I think in the article I had sent they just used index.js as a entry point but all that file did was include other files. So instead of

/map
- index.js
- style.js

it would me something like

/map
- map.component.js
- map.container.js
- map.style.js
- index.js (probably just exposes the map.container.js)

is that how you see it working?

**Comment by cmann50** [comment]
Yeah, that's exactly what I thought.  Another thing to check out is the Redux bind annotations like @connect.

**Comment by ericmasiello** [comment]
Cool. I'm not using the @connect annotation thing (but that does look cool and something i'd like to potentially adopt. I'm only a little reluctant cuz from what i understand, there's been a lot of back and forth in the JS community about decorators. They were at one point supposed to be part of ES6 (or maybe 7?) and then it got pulled out.

Anyway, I made some more edits that I think are more in line with what you had in mind. I haven't moved the container code up yet into sub directories. We can handle that in a future refactoring effort.

**Pull request merged**
