### PR TITLE
feature/working-redux

### PR DESCRIPTION
**Pull request by ericmasiello**
Basic redux is working for syncronous actions. This also handles blocking users from going to any page w/o first being loggged in.

Still need to wire up redux to support async operations for fetching data from Firebase. I'll do that in a seprarte branch & PR once this one is merged

### CODE REVIEW

**Comment by ericmasiello** [comment]
@cmann50 this would likely require a larger review so you understand the structure of the app. Maybe we can peel off some time to review either this week or weekend. If you have any immediate questions or comments, please let me know.

**Comment by cmann50** [comment]
I'm free tonight and tomorrow if you'd like to go over it (also this weekend).    Maybe at like 7pm or 8pm?

For the manual binds you are doing in the constructor:

  this.onLogin = this.onLogin.bind(this);

Did you decide against doing the autobind syntax trick from here:

https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding

class Counter extends React.Component {
  tick = () => {
    ...
  }
  ...
}

**Comment by ericmasiello** [comment]
Ohhh. i didn't understand that before. Now I get it. Okay, would you like me to make those updates?

As far as linking up, I'm teaching in the evenings on Mondays and Wednesdays so I won't be available. I can possibly do tomorrow evening. I can also probably carve out some time during lunch if you wanna get on Skype then either today or tomorrow?

**Comment by cmann50** [comment]
You could make the updates or just create a ticket and I can do it.  Up to you.  I like the syntax better than manually binding since it cleans up the code.  

Lunch doesn't work so good for me, but I blocked of 7pm tomorrow.  If you can't make it, no worries we'll just look at it over the weekend.

**Pull request merged**
